// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: excel.proto

package excels

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tax struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsPstValid bool   `protobuf:"varint,1,opt,name=IsPstValid,proto3" json:"IsPstValid,omitempty"`
	IsQstValid bool   `protobuf:"varint,2,opt,name=IsQstValid,proto3" json:"IsQstValid,omitempty"`
	PstNumber  string `protobuf:"bytes,3,opt,name=PstNumber,proto3" json:"PstNumber,omitempty"`
	QstNumber  string `protobuf:"bytes,4,opt,name=QstNumber,proto3" json:"QstNumber,omitempty"`
	Enterprise string `protobuf:"bytes,5,opt,name=Enterprise,proto3" json:"Enterprise,omitempty"`
	Date       string `protobuf:"bytes,6,opt,name=Date,proto3" json:"Date,omitempty"`
}

func (x *Tax) Reset() {
	*x = Tax{}
	if protoimpl.UnsafeEnabled {
		mi := &file_excel_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tax) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tax) ProtoMessage() {}

func (x *Tax) ProtoReflect() protoreflect.Message {
	mi := &file_excel_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tax.ProtoReflect.Descriptor instead.
func (*Tax) Descriptor() ([]byte, []int) {
	return file_excel_proto_rawDescGZIP(), []int{0}
}

func (x *Tax) GetIsPstValid() bool {
	if x != nil {
		return x.IsPstValid
	}
	return false
}

func (x *Tax) GetIsQstValid() bool {
	if x != nil {
		return x.IsQstValid
	}
	return false
}

func (x *Tax) GetPstNumber() string {
	if x != nil {
		return x.PstNumber
	}
	return ""
}

func (x *Tax) GetQstNumber() string {
	if x != nil {
		return x.QstNumber
	}
	return ""
}

func (x *Tax) GetEnterprise() string {
	if x != nil {
		return x.Enterprise
	}
	return ""
}

func (x *Tax) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type TaxRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaxEntry *Tax `protobuf:"bytes,1,opt,name=taxEntry,proto3" json:"taxEntry,omitempty"`
}

func (x *TaxRequest) Reset() {
	*x = TaxRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_excel_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaxRequest) ProtoMessage() {}

func (x *TaxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_excel_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaxRequest.ProtoReflect.Descriptor instead.
func (*TaxRequest) Descriptor() ([]byte, []int) {
	return file_excel_proto_rawDescGZIP(), []int{1}
}

func (x *TaxRequest) GetTaxEntry() *Tax {
	if x != nil {
		return x.TaxEntry
	}
	return nil
}

type TaxResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result []byte `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *TaxResponse) Reset() {
	*x = TaxResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_excel_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaxResponse) ProtoMessage() {}

func (x *TaxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_excel_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaxResponse.ProtoReflect.Descriptor instead.
func (*TaxResponse) Descriptor() ([]byte, []int) {
	return file_excel_proto_rawDescGZIP(), []int{2}
}

func (x *TaxResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_excel_proto protoreflect.FileDescriptor

var file_excel_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x65, 0x78, 0x63, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x65,
	0x78, 0x63, 0x65, 0x6c, 0x22, 0xb5, 0x01, 0x0a, 0x03, 0x54, 0x61, 0x78, 0x12, 0x1e, 0x0a, 0x0a,
	0x49, 0x73, 0x50, 0x73, 0x74, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0a, 0x49, 0x73, 0x50, 0x73, 0x74, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a,
	0x49, 0x73, 0x51, 0x73, 0x74, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0a, 0x49, 0x73, 0x51, 0x73, 0x74, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09,
	0x50, 0x73, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x50, 0x73, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x51, 0x73,
	0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x51,
	0x73, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x45, 0x6e, 0x74, 0x65,
	0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x45, 0x6e,
	0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x44, 0x61, 0x74, 0x65, 0x22, 0x34, 0x0a, 0x0a,
	0x54, 0x61, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x08, 0x74, 0x61,
	0x78, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x65,
	0x78, 0x63, 0x65, 0x6c, 0x2e, 0x54, 0x61, 0x78, 0x52, 0x08, 0x74, 0x61, 0x78, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x22, 0x25, 0x0a, 0x0b, 0x54, 0x61, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x3f, 0x0a, 0x0c, 0x45, 0x78, 0x63,
	0x65, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2f, 0x0a, 0x06, 0x55, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x12, 0x11, 0x2e, 0x65, 0x78, 0x63, 0x65, 0x6c, 0x2e, 0x54, 0x61, 0x78, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x65, 0x78, 0x63, 0x65, 0x6c, 0x2e, 0x54,
	0x61, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x09, 0x5a, 0x07, 0x2f, 0x65,
	0x78, 0x63, 0x65, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_excel_proto_rawDescOnce sync.Once
	file_excel_proto_rawDescData = file_excel_proto_rawDesc
)

func file_excel_proto_rawDescGZIP() []byte {
	file_excel_proto_rawDescOnce.Do(func() {
		file_excel_proto_rawDescData = protoimpl.X.CompressGZIP(file_excel_proto_rawDescData)
	})
	return file_excel_proto_rawDescData
}

var file_excel_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_excel_proto_goTypes = []interface{}{
	(*Tax)(nil),         // 0: excel.Tax
	(*TaxRequest)(nil),  // 1: excel.TaxRequest
	(*TaxResponse)(nil), // 2: excel.TaxResponse
}
var file_excel_proto_depIdxs = []int32{
	0, // 0: excel.TaxRequest.taxEntry:type_name -> excel.Tax
	1, // 1: excel.ExcelService.Upload:input_type -> excel.TaxRequest
	2, // 2: excel.ExcelService.Upload:output_type -> excel.TaxResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_excel_proto_init() }
func file_excel_proto_init() {
	if File_excel_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_excel_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tax); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_excel_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaxRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_excel_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaxResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_excel_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_excel_proto_goTypes,
		DependencyIndexes: file_excel_proto_depIdxs,
		MessageInfos:      file_excel_proto_msgTypes,
	}.Build()
	File_excel_proto = out.File
	file_excel_proto_rawDesc = nil
	file_excel_proto_goTypes = nil
	file_excel_proto_depIdxs = nil
}
